spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/terminal?serverTimezone=UTC&characterEncoding=UTF-8
    username: test
    password: 1234
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      properties:
      hibernate:
      show_sql: true
      format_sql: true

  messages:
    basename: messages, errors

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false



logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

